version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - ai-service
      - export-service
      - cv-review-service
      - auth-service
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "512M"
    cpus: 0.5

  user-service:
    build: ./microservices/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "8192M"
    mem_reservation: "4096M"
    cpus: 1.0
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192

  auth-service:
    build: ./microservices/auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "4096M"
    mem_reservation: "2048M"
    cpus: 0.5

  ai-service:
    build: ./microservices/ai-service
    container_name: ai-service
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "4096M"
    mem_reservation: "2048M"
    cpus: 0.5

  export-service:
    build: ./microservices/export-service
    container_name: export-service
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "8192M"
    mem_reservation: "4096M"
    cpus: 1.0
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192

  cv-review-service:
    build: ./microservices/cv-review-service
    container_name: cv-review-service
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "4096M"
    mem_reservation: "2048M"
    cpus: 0.5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: "4096M"
    mem_reservation: "2048M"
    cpus: 0.5

networks:
  app-network:
    driver: bridge
