prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        release: monitoring
    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    ruleSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
          storageClassName: managed-csi
    resources:
      requests:
        memory: "100Mi"
        cpu: "25m"
      limits:
        memory: "300Mi"
        cpu: "50m"

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: "50Mi"
        cpu: "25m"
      limits:
        memory: "200Mi"
        cpu: "50m"

grafana:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    enabled: true

kubeStateMetrics:
  enabled: true
  serviceMonitor:
    enabled: true

nodeExporter:
  enabled: true
  serviceMonitor:
    enabled: true

coreDns:
  enabled: true
  serviceMonitor:
    enabled: true

kubeControllerManager:
  enabled: true
  service:
    enabled: true
  serviceMonitor:
    enabled: true

kubeScheduler:
  enabled: true
  service:
    enabled: true
  serviceMonitor:
    enabled: true

kubeEtcd:
  enabled: false

commonLabels:
  release: monitoring
