name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-microservices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, ai-service, export-service, cv-review-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for ${{ matrix.service }}
        run: |
          cd microservices/${{ matrix.service }}
          npm ci
        continue-on-error: true # Allow this step to continue even if it fails

      - name: Run tests and generate coverage for ${{ matrix.service }}
        run: |
          cd microservices/${{ matrix.service }}
          npm test -- --coverage  # Run tests for each microservice
        continue-on-error: true # Allow this step to continue even if it fails

      - name: Build ${{ matrix.service }} Docker image
        run: |
          cd microservices/${{ matrix.service }}
          docker compose build
        continue-on-error: true # Allow this step to continue even if it fails

  sonarcloud-analysis:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build-microservices
    if: success() # Only run SonarCloud analysis if build-microservices succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-services:
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    if: success() # Only deploy if SonarCloud scan is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy services with Docker Compose
        run: docker compose up --build -d

      - name: Check running containers
        run: docker ps
